source $HOME/.config/nvim/plugin.vim
source $HOME/.config/nvim/latex.vim
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/ranger.vim
source $HOME/.config/nvim/keybind.vim
source $HOME/.config/nvim/theme.vim
source $HOME/.config/nvim/airline.vim
source $HOME/.config/nvim/vimwiki.vim
source $HOME/.config/nvim/fzf.vim
